DECLARE
A NUMBER :=&A;
B NUMBER :=&B;
C NUMBER :=&C;
BEGIN
IF A>B AND A>C THEN
DBMS_OUTPUT.PUT_LINE(A||' IS THE BIGGEST NO');
ELSIF B>A AND B>C THEN
DBMS_OUTPUT.PUT_LINE(B||' IS THE BIGGEST NO');
ELSE
DBMS_OUTPUT.PUT_LINE(C||' IS THE BIGGEST NO');
END IF;
END;