DECLARE
X CHAR(1) := '&X';
BEGIN
IF X = 'A' OR X = 'E' OR X = 'I' OR X = 'O' OR X = 'U'
THEN
DBMS_OUTPUT.PUT_LINE(X||' IS A VOWEL CHARACTER');
ELSE
DBMS_OUTPUT.PUT_LINE(X||'IS NOT A VOWEL CHARACTER');
END IF;
END;